networks:
  lab2-network:
    driver: bridge

services:
  postgres:
    container_name: lab2db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: task2
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - lab2-network

#  zipkin:
#    image: openzipkin/zipkin
#    container_name: zipkin
#    ports:
#      - "9411:9411"
#    restart: unless-stopped